# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x06\x64\x65vice\"W\n\x0e\x43ommandRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12$\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x13.device.CommandType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"[\n\x0f\x43ommandResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12$\n\x06status\x18\x02 \x01(\x0e\x32\x14.device.ResponseType\x12\x0f\n\x07message\x18\x03 \x01(\t*F\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06STATUS\x10\x01\x12\t\n\x05START\x10\x02\x12\x08\n\x04STOP\x10\x03\x12\t\n\x05RESET\x10\x04*+\n\x0cResponseType\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x08\n\x04\x42USY\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=206
  _globals['_COMMANDTYPE']._serialized_end=276
  _globals['_RESPONSETYPE']._serialized_start=278
  _globals['_RESPONSETYPE']._serialized_end=321
  _globals['_COMMANDREQUEST']._serialized_start=24
  _globals['_COMMANDREQUEST']._serialized_end=111
  _globals['_COMMANDRESPONSE']._serialized_start=113
  _globals['_COMMANDRESPONSE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
